parameters:
    ezpublish.fieldType.eztags.class: Masev\TagBundle\FieldType\Tag\Type
    ezpublish.fieldType.eztags.tagservice.class: Masev\TagBundle\FieldType\Tag\TagService
    ezpublish.fieldType.eztags.externalStorage.class: Masev\TagBundle\FieldType\Tag\TagStorage
    ezpublish.fieldType.eztags.storage_gateway.class: Masev\TagBundle\FieldType\Tag\TagStorage\Gateway\LegacyStorage
    ezpublish.fieldType.eztags.converter.class: Masev\TagBundle\FieldType\Persistence\Legacy\Converter\Tag

services:
    ezpublish.fieldType.eztags:
        class: %ezpublish.fieldType.eztags.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: eztags}

    ezpublish.fieldType.eztags.tagservice:
        class: %ezpublish.fieldType.eztags.tagservice.class%
        arguments: [@ezpublish.fieldType.eztags.externalStorage]

    ezpublish.fieldType.eztags.externalStorage:
            class: %ezpublish.fieldType.eztags.externalStorage.class%
            tags:
               - {name: ezpublish.fieldType.externalStorageHandler, alias: eztags}

    ezpublish.fieldType.eztags.storage_gateway:
            class: %ezpublish.fieldType.eztags.storage_gateway.class%
            tags:
                - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: eztags, identifier: LegacyStorage}

    ezpublish.fieldType.eztags.converter:
            class: %ezpublish.fieldType.eztags.converter.class%
            tags:
                - {name: ezpublish.storageEngine.legacy.converter, alias: eztags}